#!/bin/bash

#
# ~Dank Shell Manager~
# 

# Configuration, set SHELL_USER to the user's name (So we don't confuse systemd)
SHELL_USER="dan"
MAX_LOG_ENTRIES=50

# Vars
SHELLMAN_DIR=/home/"${SHELL_USER}"/.local/share/shellman
SHELL_STATUS=${SHELLMAN_DIR}/shellstatus
SHELL_LOG=${SHELLMAN_DIR}/shellman.log
CURRENT_USER=$USER
PARENT_PROCESS_PID=$PPID
PARENT_PROCESS=
TRACKED_SHELL=$SHELL

# Initial shell status
XSERVER_RUNNING=false
SHELL_COUNT=0
LOG_ENTRIES=0

# Option flags
SHELLMAN_DEBUG=false
LOGIN=false
LOGOUT=false
REINITIALIZE=false
DISPLAY_STATUS=false
REGISTER_XORG_INSTANCE=false
REGISTER_XORG_HALT=false
VERBOSITY=false

# Identify parent process
PARENT_PROCESS=$(awk ' $2 ~ parentPid { print $11 } ' parentPid="$PARENT_PROCESS_PID" <(ps -aux | grep $PARENT_PROCESS_PID))

# Functions
function displayLog() {
	cat ${SHELL_LOG} | less
}
function logEntry() {
	local LOG_MESSAGE=$@

	if [[ "$LOG_ENTRIES" -gt "$MAX_LOG_ENTRIES" ]]; then
		echo > ${SHELL_LOG}
		LOG_ENTRIES=0
	fi
	
	((LOG_ENTRIES++))
	date >> ${SHELL_LOG}	
	echo ${LOG_MESSAGE[@]} >> ${SHELL_LOG}
}
function retrieveCurrentConfig() {
	# Import current shell status
	if ! test -e ${SHELL_STATUS}; then
		echo "Initializing ${SHELL_STATUS} file."
		touch ${SHELL_STATUS}
		updateShellStatus
	else
		XSERVER_RUNNING=$(awk '/XSERVER_RUNNING/ { print $2 }' ${SHELL_STATUS})
		SHELL_COUNT=$(awk '/SHELL_COUNT/ { print $2 }' ${SHELL_STATUS})
		LOG_ENTRIES=$(awk '/LOG_ENTRIES/ { print $2 }' ${SHELL_STATUS})
	fi
}
function displayCurrentConfig() {
	echo "Current shellman status:"
	echo "XSERVER_RUNNING: ${XSERVER_RUNNING}"
	echo "SHELL_COUNT: ${SHELL_COUNT}"
	echo "LOG_ENTRIES: ${LOG_ENTRIES}"
	echo
}
function reinitializeStatus() {
	logEntry "Reinitializing Shell Status file."
	printf "XSERVER_RUNNING false\n" > $SHELL_STATUS
	printf "SHELL_COUNT 0\n" >> $SHELL_STATUS
	if [ -z ${LOG_ENTRIES} ]; then
		LOG_ENTRIES=0
	fi
	printf "LOG_ENTRIES %s\n", ${LOG_ENTRIES} >> $SHELL_STATUS
}
function registerXorgInstance() {
	if [ "$XSERVER_RUNNING" == true ]; then
		 logEntry "registerXorgInstance function called when XSERVER_RUNNING == true!"
	else
		XSERVER_RUNNING=true
		logEntry "Registered Xorg Instance"
	fi
}
function registerXorgHalted() {
	if [ "$XSERVER_RUNNING" == false ]; then
		logEntry "registerXorgHalted called while XSERVER_RUNNING == false!"
	fi
	XSERVER_RUNNING=false
	logEntry "Registered Xorg halt"
}
function shellLogin() {
	local CALLER=$@
	
	((SHELL_COUNT++))
	updateShellStatus
	
	logEntry "Login, called by: ${PARENT_PROCESS} PID: ${PARENT_PROCESS_PID}"
}
function shellLogout() {
	if [ "${SHELL_COUNT}" == 1 ]; then
		registerXorgHalted
		SHELL_COUNT=0;
	elif test ${SHELL_COUNT} -gt 0; then
		((SHELL_COUNT--))
	else
		logEntry "Logout called when SHELL_COUNT less than 1. Check shellman config."
	fi
	updateShellStatus
	logEntry "Logout called"
}
function updateShellStatus() {
	echo "XSERVER_RUNNING" ${XSERVER_RUNNING} > ${SHELL_STATUS}
	echo "SHELL_COUNT" ${SHELL_COUNT} >> ${SHELL_STATUS}
	echo "LOG_ENTRIES" ${LOG_ENTRIES} >> ${SHELL_STATUS}
}
function debugShellman() {
	if ! [ $SHELLMAN_DEBUG == false ]; then
		echo "Debug function called"
		echo
		echo Internal Variables:
		echo XSERVER_RUNNING ${XSERVER_RUNNING}
		echo SHELL_COUNT ${SHELL_COUNT}
	fi
}
function determineShellCount() {
	local DETERMINED_SHELL_COUNT=$(awk ' BEGIN { determinedCount=0 } $2 ~ parentPid { if ( ! /xfce/ ) { determinedCount++ } else { if ( $2 > parentPid ) { doNothing++ } } } END { print determinedCount } ' parentPid="$PARENT_PROCESS_PID" <(ps -aux | grep bash))
	logEntry "determineShellCount returned: $DETERMINED_SHELL_COUNT"
}
function main() {
	if [ "$REINITIALIZE" == true ]; then
		reinitializeStatus;
	fi
	retrieveCurrentConfig
	if [ "$LOGIN" == true ] && [ "$LOGOUT" == true ]; then
		logEntry "Attempted to login and logout in same call."
		echo && exit;
	fi
	
	if [ "$LOGOUT" == true ]; then
		shellLogout;
	elif [ "$LOGIN" == true ]; then
		shellLogin $0;
	fi
	if [ "$REGISTER_XORG_INSTANCE" == true ]; then
		registerXorgInstance
	elif [ "$REGISTER_XORG_HALT" == true ]; then
		registerXorgHalted
	fi
	if [ "$SHELLMAN_DEBUG" == true ]; then
		debugShellman;
	fi;
	
	updateShellStatus;
	determineShellCount;
	exit;
}

#Initialize config directory
if test ! -d "${SHELLMAN_DIR}"; then
	echo "Initializing config directory in ${HOME}/.local/share"
	mkdir "${SHELLMAN_DIR}"
fi

#Parse args
if test ! $# -eq 0; then
	for ARGUMENT in "$@"; do
		case $ARGUMENT in
			-s|--status)
				retrieveCurrentConfig
				determineShellCount
				displayCurrentConfig
				exit
				;;
			-d|--debug)
				SHELLMAN_DEBUG=true
				;;
			-x|--registerxorg)
				REGISTER_XORG_INSTANCE=true
				;;
			-h|--)
				REGISTER_XORG_HALT=true
				;;
			-l|--login)
				LOGIN=true
				;;
			-o|--logout)
				LOGOUT=true
				;;
			-r|--reinitialize)
				REINITIALIZE=true
				;;
			--sysd)
				logEntry "Called with --sysd argument"
				;;
			-v|--verbose)
				VERBOSITY=true
				;;
			--display-log)
				displayLog
				exit
				;;
			*)
				logEntry "Shellman called with unknown args!"
				echo && exit
				;;
		esac
	done
else
	logEntry "No arguments passed. Exiting"
	if [ ${SHELLMAN_DEBUG} == true ]; then
		debugShellman
	fi
	echo && exit;
fi

main
